### ISSUE TITLE
Order of Encounters in Edit an Encounter

### ISSUE THREAD

**Issue by marajha** [beaugunderson/tracking-tool#21]
![screen shot 2018-11-26 at 16 20 21](https://user-images.githubusercontent.com/45274708/49050254-5a2c2b80-f197-11e8-97eb-056c8cf24e4f.png)

One of the encounters seems to appear out of order, not sure why...  I wonder if this is one where I changed the Encounter Date field and so there's a discrepancy between the date I said the encounter took place and when it was logged?

**Comment by beaugunderson** [comment]
october vs. november 😄
