### ISSUE TITLE
Weird Edit/Patient bug

### ISSUE THREAD

**Issue by marajha** [beaugunderson/tracking-tool#29]
We were talking last night about how it deleted some of your patient names from the dropdown because you changed how it logged something, it did the same for me.  When I click on those patient's encounters on the Edit screen it doesn't take me into one of the encounters, but if I then click on Patient to create a new entry it will instead fill it with all the data from the encounter that it doesn't believe exists.  Not sure if this is a thing that needs fixing, but thought I would point it out in case it does.

**Comment by beaugunderson** [comment]
this is the one i mentioned that would affect the encounters you made prior to some changes i made--with the addition of the "Generate example encounters" button i don't think it's worth fixing your file manually
