### ISSUE TITLE
Change graphs to use tasks/encounters instead of entries

### ISSUE THREAD

**Issue by marajha** [beaugunderson/tracking-tool#64]
![screen shot 2018-12-27 at 07 20 50](https://user-images.githubusercontent.com/45274708/50484971-17cd5880-09a8-11e9-8aac-13f1d14b1837.png)

I thought maybe it was task number, but when I hover over my name it says 98 and when I look at the task count at the top of the page it says 178.  It's not unique patients either, the count at the top for that is 50.

**Comment by beaugunderson** [comment]
i believe it's "entries", meaning number of times the patient form has been submitted... what should it show to be most useful?

**Comment by marajha** [comment]
>i believe it's "entries", meaning number of times the patient form has been submitted... what should it show to be most useful?

@beaugunderson let’s talk about it tonight

**Comment by beaugunderson** [comment]
- [ ] make age use unique patients only (not entries)
- [ ] change top graph to use tasks (which are encounters) instead of entries
- [ ] change social worker graph to use tasks (encounters)
- [ ] audit other graphs, if they use entries instead use tasks (encounters)
