### ISSUE TITLE
Need to update description for "Care Coordination"

### ISSUE THREAD

**Issue by beaugunderson** [beaugunderson/tracking-tool#85]
I'll get it to you this weekend

**Comment by marajha** [comment]
Description: "Can include chart review, coordination or communication with patient, internal or external care team members (SW/CM, MD, PA/NP, RN, MA, PSC), etc. Excludes Home Care, Facility; Palliative Care, Hospice; Psychiatry, Psychotherapy - these should be tracked using the more specific categories"
